/**
 * Debitoor.com Api Client
 * This is an unofficial api client for the debitoor api. Still in development, don´t use it in production! More information at [https://developers.debitoor.com/api-reference](https://developers.debitoor.com/api-reference).
 *
 * OpenAPI spec version: 0.0.1
 * Contact: pascal.wild@mallorca-software.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.mallorcasoftware.debitoorapiclient.api;

import com.mallorcasoftware.debitoorapiclient.ApiException;
import com.mallorcasoftware.debitoorapiclient.model.CountryDto;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CountriesApi
 */
public class CountriesApiTest {

    private final CountriesApi api = new CountriesApi();

    
    /**
     * 
     *
     * Get sorted list of countries translated to the specified language 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCountriesTranslatedByLanguageCodeTest() throws ApiException {
        String languagecode = null;
        // List<CountryDto> response = api.getCountriesTranslatedByLanguageCode(languagecode);

        // TODO: test validations
    }
    
}
